
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    build: ./web
    hostname: web1
    ports:
      - '81:5000'
  web2:
    restart: on-failure
    build: ./web
    hostname: web2
    ports:
      - '82:5000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2
  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis
    restart: always

    # environment:
    #   - REDIS_0_HOST=redis
    #   - REDIS_0_PORT=6379
    #   - REDIS_0_PASSWORD=your_redis_password
    #   - REDIS_0_TLS=false
    #   - REDIS_0_NAME=MyRedis

